<style type=text/css>

#dhtmltooltip {
position: absolute;
width: 150px;
border: 2px solid black;
padding: 2px;
background-color: lightyellow;
visibility: hidden;
z-index: 100;
/*Remove below line to remove shadow. Below line should always appear last within this CSS*/
filter: progid:DXImageTransform.Microsoft.Shadow(color=gray,direction=135);
}

</style>

	<style type="text/css">
		 body {
		 scrollbar-arrow-color: white;
		 scrollbar-dark-shadow-color: #000080;
		 scrollbar-track-color: #0080C0;
		 scrollbar-face-color: #000080;
		 scrollbar-shadow-color: white;
		 scrollbar-highlight-color: white;
		 scrollbar-3d-light-color: a;
		 overflow: auto;
		 overflow-x: hidden;
		 scrollbar-base-color:#ffeaff:


		 }
	 </style>
