<%
'Set ConexionOra = Server.CreateObject("ADOdb.Connection")
'ConexionOra.Open "Provider=OraOLEDB.Oracle;Data Source=net_orion;User Id=SCC;PASSWORD=andromeda;"


'13223752-2

'Set ConeOra = Server.CreateObject("ADOdb.Connection")
'ConexionOra.Open "uid=scc;pwd=andromeda;driver={Microsoft ODBC for Oracle};server=net_orion"

    'Conexion = "Data Source=net_orion;User Id=SCC;PASSWORD=andromeda;"
    

'    Conexion = "uid=usr_scg;pwd=usr_scg;server=ICARUS;database=SCG"
'    ConeOra.CommandTimeout = 500
'    ConeOra.ConnectionTimeout = 500
'    'ConeOra.Provider = "OraOLEDB.Oracle"
'    ConeOra.Provider = "{SQL Server}"
'    ConeOra.Open Conexion




'ConexionOra.Open "Provider=OraOLEDB.Oracle;Data Source=ora_ds;User ID=scc;Password=andromeda;"
'ConexionOra.Open "Provider=OraOLEDB.Oracle;Data Source=ora_orion2;User ID=scc;Password=andromeda;"

'ConexionOra.Open "Provider=OraOLEDB.Oracle;Data Source=net_orion;User Id=SCC;PASSWORD=andromeda;"


'ConexionOra.Open "Provider=OraOLEDB.Oracle.1;Password=andromeda ;Persist Security Info=True;User ID=scc;Data Source=net_orion"

'ConexionOra.Open "DRIVER={Microsoft ODBC for Oracle};DSN=scc;Password=andromeda;User ID=scc"

'ConexionOra.Open "Driver = {Microsoft ODBC for Oracle};Server=net_orion;uid=scc;pwd=andromeda"
'ConexionOra.Open "dsn=scc;uid=scc;pwd=andromeda;"


'Session("intConfServidor") = "Ingles"
'Session("PrecisionDouble") = 10
%>


